/*insert the names ROLE_USER and ROLE_ADMIN into the roles table if the dont exist*/
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User data');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Observations');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Interviews');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Customer feedback');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Problem statement');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Multidisciplinary team');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Creative space/environment');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Concept design');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Tools and materials');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Current market trends');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Competitor analysis');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Business goals');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Customer profiles');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Product/service features');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Market research data');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Design challenge');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Team');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Facilitator');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Internal business data (strengths, weaknesses)');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('External market data (opportunities, threats)');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Central problem or topic');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Related subtopics');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Creative thinking');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User personas');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User goals');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Touchpoints');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Interactions');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User selection');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Question set');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Interview protocol');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User empathy map');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Improved understanding of user needs and motivations');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Better user personas');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Multiple ideas');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Innovative concepts');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Expanded problem understanding');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Physical or digital prototypes');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Improved product design');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User testing results');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Future scenarios');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Risk and opportunity assessment');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Strategic planning');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Value proposition');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Improved product-market fit');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Customer journey mapping');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Tested prototype');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Validated ideas');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Solutions to design problems');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('SWOT matrix');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Strategic insights');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Plan for leveraging strengths and opportunities');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Plan for addressing weaknesses and threats');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Visual map of related ideas or concepts');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('New connections and insights');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Visual map of the users experience');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Pain points identification');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Areas for improvement');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('User feedback');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Insights into user behavior and motivations');
INSERT INTO inputs_outputs (inputs_outputs) VALUES ('Improved understanding of user needs');

